// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsQSWPzRrNklLFFoHDWj4uI8fHfPq9XcY',
    appId: '1:1091784674706:web:44b1a008ee38ae92c7054b',
    messagingSenderId: '1091784674706',
    projectId: 'fitblock-ad8cd',
    authDomain: 'fitblock-ad8cd.firebaseapp.com',
    storageBucket: 'fitblock-ad8cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqJ_wDl2iV1vbf-MkhRLBN2eURW_P5wQE',
    appId: '1:1091784674706:android:eb9028ef4c52ef6bc7054b',
    messagingSenderId: '1091784674706',
    projectId: 'fitblock-ad8cd',
    storageBucket: 'fitblock-ad8cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ3xRQNoteDipzhW2aUke48eb_jP3hkjg',
    appId: '1:1091784674706:ios:33f5607a2da7bc05c7054b',
    messagingSenderId: '1091784674706',
    projectId: 'fitblock-ad8cd',
    storageBucket: 'fitblock-ad8cd.appspot.com',
    iosBundleId: 'com.example.fitblock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ3xRQNoteDipzhW2aUke48eb_jP3hkjg',
    appId: '1:1091784674706:ios:bfdba3c96166f6cac7054b',
    messagingSenderId: '1091784674706',
    projectId: 'fitblock-ad8cd',
    storageBucket: 'fitblock-ad8cd.appspot.com',
    iosBundleId: 'com.example.fitblock.RunnerTests',
  );
}
